name: ds_learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  # Core Data Science
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - statsmodels>=0.14  # Fixes the decorator bug found in older versions
  - setuptools   
  # Notebook Environment
  - jupyter
  - ipykernel
  - notebook
  # Utilities
  - tqdm
  - openpyxl
  # Plotly + Cufflinks
  - plotly
  - cufflinks-py
  - pip:
    - ydata-profiling  # Installed via pip to get the latest 4.12+ version
    - nbformat>=4.2.0 # Required for plotly in VS Code