name: learning
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - seaborn
  - scipy
  - plotly::chart-studio
  - main::plotly
  - cufflinks-py
  - scikit-learn
  - pip:
    - nbformat>=4.2.0 # Required for plotly in VS Code